create table ranks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  vv int not null default 0,
  is_complete boolean default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table ranks enable row level security;
create policy "Individuals can create ranks." on ranks for
    insert with check (auth.uid() = user_id);
create policy "Individuals can update their own ranks." on ranks for
    update using (auth.uid() = user_id);
create policy "Individuals can delete their own ranks." on ranks for
    delete using (auth.uid() = user_id);

create policy "Ranks are public." on ranks for
    select using ( true );

